# Generated by Django 4.2.23 on 2025-09-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('alternaria_leaf_spot', 'Alternaria Leaf Spot'), ('club_root', 'Club Root'), ('downy_mildew', 'Downy Mildew'), ('cabbage_aphid_colony', 'Cabbage Aphid Colony'), ('ring_spot', 'Ring Spot'), ('black_rot', 'Black Rot'), ('bacterial_spot_rot', 'Bacterial Spot Rot'), ('no_disease', 'No Disease')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('treatment', models.TextField()),
                ('prevention', models.TextField()),
                ('best_practices', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
